### PR TITLE
Use Char over String wherever possible

### PR DESCRIPTION
**Pull request by Sija**
Bit of performance optimization ain't hurt any1.

### CODE REVIEW

**Comment by Blacksmoke16** [comment]
:100: Nice one.  However it seems the specs are failing.

**Comment by Sija** [comment]
I'm trying to find out the reason since it ain't obvious to me what would cause 'em to fail...

**Comment by Sija** [comment]
Specs fixed, ready for review :)

**Review by Blacksmoke16 — APPROVED** [review]

**Review by robacarp — APPROVED** [review]

**Comment by veelenga** [comment]
@Sija nice. Would be interesting to add such a rule to Ameba. Are there some guidelines where and when this can/cannot be replaced?

**Comment by Blacksmoke16** [comment]
@veelenga Usually when its a single character or special char, like `'a'` or `'\n'` that isn't an empty string.

For example the one case I know of, is in `String#gsub`.  Where if you had like `"foo bar".gsub(' ',"")` Replacing the `""` like `"foo bar".gsub(' ','')` wouldn't compile since its an empty string literal.

**Comment by Sija** [comment]
@veelenga I think it would be a neat case for adding as a rule. My rule of thumb is checking for regex pattern `/"(.)"/` matching arguments passed to `String#[]?/[]/sub/gsub/index/rindex/join/split/includes?/ends_with?/starts_with?/lchop/rchop/lstrip/rstrip/strip/chomp` and possibly some others I've missed :)

**Pull request merged**
